[build]
  command = "npm run build"
  publish = "dist"
  directory = "dist"

[build.environment]
  VITE_API_URL = "https://crypto-backend-7uwg.onrender.com/api"

[[redirects]]
  from = "/api/*"
  to = "https://crypto-backend-7uwg.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200